### ISSUE TITLE
Update to 1.0

### ISSUE THREAD

**Issue by Tazer** [domaindrivendev/Ahoy#111]
Hey! :) Doing the upgrade to .net core 1.0 soon ?

**Comment by tillig** [comment]
First, thanks to @domaindrivendev for this great package. It's one of the core things for REST on .NET that's pretty indisposable at this point, at least for me.

While I recognize the challenges of keeping up with the .NET Core stuff (I'm having similar challenges with [Autofac](https://github.com/autofac/Autofac)), I do see that there are several issues and pull requests here that could help speed things along in getting this out for ASP.NET Core. As it stands, my team is consuming custom builds of this package off our own internal NuGet server.

@domaindrivendev If you're interested, I and my team would like to help. I'd prefer that to forking and having to own the whole thing ourselves. If I/we could accept PRs on your behalf or, at the very least, get this up and running on the RTM bits and published to NuGet in beta, that'd be awesome. If you're interested, drop me a line - my email is my username at `paraesthesia.com`. Until then, I'll be updating all of this to run on ASP.NET Core in my fork since it appears I'm running into some type load issues due to breaking interface changes in the RTM bits.

No pressure, and again, tons of thanks for all the great work so far.

**Comment by npnelson** [comment]
I don't know if this helps, but here is one of the things that changed between RC2 and RTM that impacts this project. https://github.com/aspnet/Routing/pull/303.  I'm not sure how to fix it though, I haven't had the opportunity to work with TemplateMatcher.

I also want to say that this is an awesome package and has become indispensable for my work as well.

**Comment by bradygaster** [comment]
+1000 to what @tillig said regarding the project and how awesome it is. i'd love to see the 1.0 release coming out soon. I'm the project's biggest fan - @domaindrivendev can back me up on this. :)

**Comment by tillig** [comment]
For reference / anyone interested, [I have a branch in my fork building against .NET Core RTM](https://github.com/tillig/Ahoy/tree/rtm-project-update).

**Comment by domaindrivendev** [comment]
@tillig - any chance you could submit a PR for this and I'll review and try get it pushed through by EOD tomorrow.

**Comment by tillig** [comment]
Added PR #112 based on my working fork/branch. Let me know if there are questions or if there's more work to do.

**Comment by IanElsinga** [comment]
Hi, AddSwaggerGen fails with Core RTM with the following exception:  

> 
Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Is this being fixed as well and when can we expect a NuGet update?  

Thanks very much.

**Comment by tillig** [comment]
@IanElsinga That's one of the _many, many_ stupid breaking changes the ASP.NET Core team introduced between RC2 and RTM. As noted above, I have it all working in a PR that's currently being looked at.

**Comment by jamesond** [comment]
Any progress on this? Thank you guys I really appreciate it!

**Comment by freerider7777** [comment]
Hi! Also waiting for new version... Hope after release there won't be such breaking changes any more...
Thanks for the great library!

**Comment by kudoz83** [comment]
Also waiting... looks like there are several PR to address which is hopeful.  We just need them to get into nuget.

**Comment by dlebedynskyi** [comment]
Waiting for PR merge as well and new nuget. Thank you guys for supporting this

**Comment by tillig** [comment]
I know there are a lot of folks interested - if instead of commenting, you could either respond with a "reaction" (use that little smiley with a "+" next to it at the top right of every issue comment) or just click the notifications "Subscribe" button (right hand column under the tags), it could help keep the rest of the issue easy to follow if there are updates so new folks coming in don't have to scroll through a lot of "me too" comments.

**Comment by another-guy** [comment]
Everything works fine for me after upgrading to fresh `6.0.0-beta901`version of nuget packages! Thanks for the fix lads!

**Comment by bradygaster** [comment]
Can't wait to try it out!

**Comment by jamesond** [comment]
Thank you guys for the fix!

**Comment by mrwcjoughin** [comment]
How did you get this or work with 6.0.0-beta901 ? i am still getting the following errors on 6.0.0-beta901:
Error CS0234: The type or namespace name 'Info' does not exist in the namespace 'Swashbuckle.SwaggerGen.Generator' (are you missing an assembly reference?)

error CS0234: The type or namespace name 'XmlComments' does not exist in the namespace 'Swashbuckle.SwaggerGen' (are you missing an assembly reference?)
'IServiceCollection' does not contain a definition for 'ConfigureSwaggerSchema' and no extension method 'ConfigureSwaggerSchema' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseSwaggerGen' and no extension method 'UseSwaggerGen' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

My project.json has the following references (which dotnet restore has no problem downloading):
"Swashbuckle": "6.0.0-beta901",
    "Swashbuckle.Swagger": "6.0.0-beta901",
    "Swashbuckle.SwaggerGen": "6.0.0-beta901",
    "Swashbuckle.SwaggerUi": "6.0.0-beta901",

**Comment by martincostello** [comment]
You need to use intellisense to find the new namespace those types have moved to.

**Comment by mrwcjoughin** [comment]
aah, didn't realise there were namespace changes. thats a little difficult in Visual Studio Code (I work on a Mac), but I have worked it out in the end and it works ! Thanks 👍

**Comment by Serjster** [comment]
What the timeline for RTM on this?
