### ISSUE TITLE
Cross platform

### ISSUE THREAD

**Issue by fleed** [domaindrivendev/Ahoy#131]
Is it possible to make the library available for other platforms (like Mac OS)?

**Comment by amweiss** [comment]
It works fine on OSX, what are you not seeing work?

**Comment by fleed** [comment]
I've tested it again. It doesn't work on Windows with latest version (6.0.0-rc1-final) with the following error:

> error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

but version 6.0.0-beta901 works just fine.
I will test it again on a Mac too, but I think we can close this issue since the problem is not compatibility.
